### ISSUE TITLE
Move away from ouroboros

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/bao-tree#12]

**Comment by dignifiedquire** [comment]
it got fixed, the latest version doesn't have undefined behaviour anymore

**Comment by rklaehn** [comment]
> it got fixed, the latest version doesn't have undefined behaviour anymore

Great, just when I was about to remove it...

**Comment by rklaehn** [comment]
Ouroboros is gone, and now that we know that ouroboros -> self-cell was not to blame for the perf regression I think we can close this.
